### ISSUE TITLE
Ability to dynamically resize images through import url

### ISSUE THREAD

**Issue by Xstoudi** [unplugin/unplugin-imagemin#108]
### What problem does this feature solve?

Could be awesome to be able to pass an expected size through import url like this to be able to even further reduce image size when appropriate.

### What does the proposed API look like?

`import background from '@/images/header-background.jpg?width=800&height=600'`

**Comment by ErKeLost** [comment]
You still want to change the picture size in the production environment, not the development environment. I don't know if this setting will affect the inconsistency between production and development in the process of development.

Because at present, the main function of the plug-in is to modify the image size in the production environment. I already have a plug-in for vite, and if you want to do it in the production environment, I will add this ability to parse query.

**Comment by ErKeLost** [comment]
I considered the issue of adding query to the image. Squoosh can pass the size parameter, but this plug-in is best used in the production environment build. If it is used in dev, the compression time may be long, and the effect will not be very good.
