### ISSUE TITLE
how about just compress once for one image/assets

### ISSUE THREAD

**Issue by buddywang** [unplugin/unplugin-imagemin#130]
### What problem does this feature solve?

for now, every image will be compressed in every build, this is a bit repetitive and wasteful

### What does the proposed API look like?

use a extra file to record which files has been compressed before, and there will no compression for those file in next build
we can use git client-side hook like pre-commit to check whether there has image not being compressed and we can compress them an update the record-file, and interrupt the commit and ask to add a new commit for new compressed file

the extra file can use the hash value of the compressed file to determine whether the file has been compressed

**Comment by buddywang** [comment]
If the author agrees with the idea, I'd be happy to contribute😀

**Comment by ErKeLost** [comment]
hi @buddywang  Thank you for your use.

1. At present, there is a cache module in the code, which will cache all the compressed images locally. If it is compressed for the first time, it will not continue to be compressed, but this module has not been released because it is not perfect because of its work.

two。. I think your idea is very interesting, but I don't know if it will involve some similar privacy issues, such as obtaining user git-related information (because I don't know the specific implementation). Another question is whether pre-commit is similar to api, because we can't guarantee that all users will install pre-commit.

Of course, if all the above problems can be solved correctly, pr is welcome, or if you like, you can continue to optimize the cache function.

**Comment by buddywang** [comment]
hi, it just my initial thought, I'm going to study it and see how to implement it

1. From your description, the original files will still be retained. Are the compressed files saved locally? Will they be submitted to the git repository? Can others use this cache? It doesn’t look like what I had in mind;

2. about how can we do this, just like `lint-staged`, it can do something like that, git hook will exist when running `git init`. For projects that do not use git, we can provide some commands to complete the same work.

If I want to contribute, will it be based on the main branch?

**Comment by buddywang** [comment]
@ErKeLost  we can get git status like this 
![image](https://github.com/unplugin/unplugin-imagemin/assets/37980587/7218f331-9d62-4b9f-a90e-054da7b08d94)

**Comment by ErKeLost** [comment]
oh, I probably understand your idea. If the local cache is stored in node_modules, the cache cannot be shared in this case. We may be able to provide two cache modes, one local and one git,fock main branch. pr welcome ！

**Comment by buddywang** [comment]
👌

**Comment by buddywang** [comment]
After some thinking, I decided it would be more appropriate to make a framework-agnostic tool. I decided to implement it in a new project, thanks to the inspiration of this project.🤔

**Comment by ErKeLost** [comment]
Well, it is possible that it would be better to make a separate tool, thank you.
