### ISSUE TITLE
Update node.js engine version

### ISSUE THREAD

**Issue by meerhimmel** [unplugin/unplugin-imagemin#68]
### Steps to reproduce

I am filling this as bug because when I tried to installl the package, I could not, acoording to errors in the console.
It iwas due to Node.js version being required, it is lower than what I have installed.

Node 18 is going to be the default soon, and Node 20 is stable and also available.
I am in Node 20 and pnpm.
I ask to remove restriction on the engine field of package.json of this project. Please  define an older version as you need, while keeping it open for us to install newer Node.js versions.

### What is expected?

To be able to install Node.js higher than required by this project.

### What is actually happening?

Error on package installation.

**Comment by ErKeLost** [comment]
Do you mean that the current node engine field affects your use? it can be used by default above 14. It should not affect your pnpm or v20. Tips squoosh only supports node 18. If you need to use node 20 or above, please use sharp.

**Comment by ErKeLost** [comment]
Updated

**Comment by ErKeLost** [comment]
> Thank you for the tip. Yeah, I do not know why the error happened before. The previous node engine field should not affect my use, but it did. Now you updated and I confirm the error is gone. 谢谢你！

That's great. Thank you for using it.

**Comment by ErKeLost** [comment]
This is supposed to be a squoosh problem. I'm thinking about whether to separate squoosh and sharp from unplugin, and what kind of dependencies you need to install them each time. Your problem is because squoosh 0.4.0 does not support node 20. I should turn production dependencies into development dependencies so that you need to use them in which node version. It's up to you to decide the next version. I'll fix this problem.

I wonder if you can lower your node version to less than 20 for the time being.

**Comment by ErKeLost** [comment]
Thank you for your advice.

For the first point, the problem with the node version is really difficult to fix because I will separate the sharp because of squoosh, because I may encounter some problems when installing sharp.

Because I didn't have time, I even wanted to maintain my own set of squoosh to help support the latest node version, because squoosh is really great.

Thank you again for your advice. I will solve the problem of sharp separation in the near future. The problem of squoosh can only be shelved for the time being.
